### ISSUE TITLE
pipeline failure on node14 smoke tests

### ISSUE THREAD

**Issue by vscheuber** [rockcarver/frodo-lib#143]
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From esm/api/ThemeApi.test.mjs.

      20 | let _curlirize = undefined;
      21 | (async function () {
    > 22 |   _curlirize = await import('axios-curlirize');
         |   ^
      23 | })();
      24 | const __dirname = path.dirname(fileURLToPath(import.meta.url));
      25 | const pkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../package.json'), 'utf8'));

      at esm/api/BaseApi.mjs:22:3
      at esm/api/BaseApi.mjs:23:3

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From esm/api/ThemeApi.test.mjs.
```

**Comment by vscheuber** [comment]
Attempting this suggestion and use fake timers and see where that takes us:

**Comment by vscheuber** [comment]
Still breaking
