### ISSUE TITLE
Pipeline github action segfaulting during smoke testing

### ISSUE THREAD

**Issue by vscheuber** [rockcarver/frodo-lib#146]
```
Segmentation fault (core dumped)
Error: Process completed with exit code 139.
```

**Comment by vscheuber** [comment]
Still happening, this time we got more info:
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From esm/api/ThemeApi.test.mjs.

      20 | let _curlirize = undefined;
      21 | (async function () {
    > 22 |   _curlirize = await import('axios-curlirize');
         |   ^
      23 | })();
      24 | const __dirname = path.dirname(fileURLToPath(import.meta.url));
      25 | const pkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../package.json'), 'utf8'));

      at esm/api/BaseApi.mjs:22:3
      at esm/api/BaseApi.mjs:23:3
```

**Comment by vscheuber** [comment]
still happening.
