### ISSUE TITLE
Fix pipeline for frodo-lib

### ISSUE THREAD

**Issue by vscheuber** [rockcarver/frodo-lib#3]

**Comment by vscheuber** [comment]
Tests are failing

**Comment by vscheuber** [comment]
Tests are still failing

**Comment by vscheuber** [comment]
1 test still failing:
```
FAIL src/ops/utils/ExportImportUtils.test.js
  ● convertBase64TextToArray returns an array of text lines in base64 encoding

    TypeError: plainText.replaceAll is not a function

      51 |   let arrayOut = [];
      52 |   let plainText = decode(b64text);
    > 53 |   plainText = plainText.replaceAll('\t', '    ');
         |                         ^
      54 |   arrayOut = plainText.split('\n');
      55 |   return arrayOut;
      56 | }

      at replaceAll (src/ops/utils/ExportImportUtils.js:53:25)
      at Object.convertBase64TextToArray (src/ops/utils/ExportImportUtils.test.js:26:18)
```
